# 系统风控配置文件

[database]
uri = "mysql://companytest:ZNvC5NoLJNnO3Wn0@uat-stock-data.chinaeast2.cloudapp.chinacloudapi.cn:13301/phoenix_stock"

[application]
apphost = "0.0.0.0"
appport = 8018

[system]
adminserver = "http://finances.metestsvr.com/"
wtserver = "finances.metestsvr.com:50072"
cacheshort = 3600                              #单位秒
cachelong = 3600                               #单位秒
persist_interval = 3600                        #数据保存时间间隔，单位秒
account_total = "1000001"                      #总账户的unit_id
basic_currency = "HKD"                         #基币

# 行情
[quotation]
amqpaddr = "amqp://pp:pp123@data.metestsvr.com:5672/%2f"
exchanger = "Stock"

# 消息中心
[notification]
amqpaddr = "amqp://pp:pp123@data.metestsvr.com:5672/%2f"
exchanger = "oms_msg"

[redis]
uri = "redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7000/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7001/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7002/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7003/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7004/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7005/"