# log4rs.yaml
# d, data 日期, 默认为 ISO 9601 格式, 可以通过 {d(%Y-%m-%d %H:%M:%S.%f)} 这种方式改变日期格
# 检查配置文件变动的时间间隔
refresh_rate: 30 seconds
# appender 负责将日志收集到控制台或文件, 可配置多个
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d} {l} {t} {L} - {m}{n}"
  file:
    kind: file
    path: "log/run.log"
    encoder:
      # log 信息模式
      #pattern: "{d} - {m}{n}"
      pattern: "{d(%+)(local)} {h({l})} {M}:{m}{n}"
  roll: #定义rooling_file的appenders
    kind: rolling_file
    encoder:
      pattern: "{d} {l} {t} {L} - {m}{n}" #"{d} {l} {t}  {L} - {m}{n}"
    path: log/run.log
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 100 mb
      roller:
        kind: fixed_window
        pattern: "log/run.log.{}"
        base: 1
        count: 5
# 对全局 log 进行配置
root:
  level: info
  appenders:
    - stdout
    - roll
