//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

pub mod prelude;

pub mod phoenix_ord_stockdeal;
pub mod phoenix_ord_stockorder;
pub mod phoenix_ord_suborder;
pub mod phoenix_ord_pendsettle;

pub mod phoenix_oms_tradeconfig;
// pub mod phoenix_ast_stockposition;

// pub mod phoenix_oms_feeset;
// pub mod phoenix_sys_dictionary;


// pub mod phoenix_account_assets;
// pub mod phoenix_account_assets_his;
// pub mod phoenix_account_reset_detail;
// pub mod phoenix_ast_frozendetail;
// pub mod phoenix_ast_frozendetail_his;
// pub mod phoenix_ast_operation_detail;
// pub mod phoenix_ast_stockposition;
// pub mod phoenix_ast_unitasset;
// pub mod phoenix_ast_unitasset_his;
// pub mod phoenix_deal_detail;
// pub mod phoenix_deal_detail_his;
// pub mod phoenix_oms_assetflow;
// pub mod phoenix_ord_settledetail;
// pub mod phoenix_risk_details;
// pub mod phoenix_stockposition_channel;
// pub mod phoenix_stockposition_channel_his;
// pub mod phoenix_sys_backconfig;
// pub mod phoenix_sys_system;
// pub mod phoenix_trans_detail;
// pub mod phoenix_user_assets;
// pub mod phoenix_user_assets_his;
