//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "phoenix_user_assets")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  #[sea_orm(unique)]
  pub p_unit_id: i32,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub en_real_cash: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub en_credit_cash: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub en_risk_capital: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub st_total_value: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub st_position_value: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub st_position_value_star: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub st_prebuy_value_star: Decimal,
  #[sea_orm(column_type = "Decimal(Some((20, 4)))")]
  pub st_position_profit: Decimal,
  pub p_date: i32,
  pub p_updatetime: i64,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    panic!("No RelationDef")
  }
}

impl ActiveModelBehavior for ActiveModel {}
