# 系统风控配置文件

[database]
uri = "mysql://companytest:ZNvC5NoLJNnO3Wn0@uat-stock-data.chinaeast2.cloudapp.chinacloudapi.cn:13301/stock"

[application]
apphost = "0.0.0.0"
appport = 60000

[system]
# adminserver = "http://uat-stock-ha.chinaeast2.cloudapp.chinacloudapi.cn:89/"
adminserver = "http://uat-stock.chinaeast2.cloudapp.chinacloudapi.cn:89/"
accountassetsserver = "127.0.0.1:50001"
wtserver = "finances.metestsvr.com:50072"
cacheshort = 3600 #单位秒
cachelong = 3600 #单位秒
hqcenterserver= "127.0.0.1:10001"

# max_shares = 300000 #单笔最大数量
# max_star_shares = 100000 #科创版单笔最大数量
# min_star_shares = 200

[notification]
# dev-data.chinaeast2.cloudapp.chinacloudapi.cn
# uat-stock-data.chinaeast2.cloudapp.chinacloudapi.cn
amqpaddr = "amqp://pp:pp123@uat-stock-data.chinaeast2.cloudapp.chinacloudapi.cn:5672/%2f"
exchanger = "phoenix_message_center"


[redis]
#The URL format is redis://[<username>][:<password>@]<hostname>[:port][/<db>]
#redis集群，通过逗号分隔
uri = "redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7000/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7001/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7002/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7003/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7004/,redis://:pl9rz1L0hbOoacesE3Jh@52.131.255.193:7005/" 
# uri = "redis://:pl9rz1L0hbOoacesE3Jh@data.metestsvr.com:6379/3"