//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "phoenix_sys_dictionary")]
pub struct Model {
  #[sea_orm(primary_key)]
  pub id: i64,
  pub dictionary_no: i32,
  pub lemma_item: String,
  pub item_name: String,
  pub allow_edit: String,
  pub code_length: i32,
  pub opposite_no: i32,
  pub opposite_item: String,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    panic!("No RelationDef")
  }
}

impl ActiveModelBehavior for ActiveModel {}
