//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::phoenix_sys_backconfig::Entity as PhoenixSysBackconfigEntity;
pub use super::phoenix_sys_dictionary::Entity as PhoenixSysDictionaryEntity;
pub use super::phoenix_sys_system::Entity as PhoenixSysSystemEntity;

pub use super::phoenix_sys_backconfig::Model as PhoenixSysBackconfig;
pub use super::phoenix_sys_dictionary::Model as PhoenixSysDictionary;
pub use super::phoenix_sys_system::Model as PhoenixSysSystem;
